# Generated by Django 2.1.8 on 2019-07-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.CharField(max_length=11, unique=True)),
                ('nickNum', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=2)),
                ('birth_year', models.IntegerField(default=1900)),
                ('birth_month', models.IntegerField(default=1)),
                ('birth_day', models.IntegerField(default=1)),
                ('avatar', models.CharField(max_length=256)),
                ('location', models.CharField(choices=[('gz', '广州'), ('bj', '北京'), ('sz', '深圳'), ('sh', '上海')], max_length=36)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
