# Generated by Django 2.1.8 on 2019-07-17 21:48

from django.db import migrations, models
import libs.orm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('gz', '广州'), ('bj', '北京'), ('sz', '深圳'), ('sh', '上海')], default='gz', max_length=36)),
                ('min_distance', models.IntegerField(default=0)),
                ('max_distance', models.IntegerField(default=5)),
                ('min_dating_age', models.IntegerField(default=18)),
                ('max_dating_age', models.IntegerField(default=81)),
                ('dating_sex', models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=2)),
                ('auto_play', models.CharField(choices=[('0', '否'), ('1', '是')], default='0', max_length=2)),
            ],
            options={
                'db_table': 'profiles',
            },
            bases=(models.Model, libs.orm.ModelToDictMixin),
        ),
    ]
