# Generated by Django 2.1.8 on 2019-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=1999),
        ),
    ]
